services:

  db:
    image: postgres:15-alpine
    container_name: db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    volumes:
      - ./postgres/data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: backend

    depends_on:
      - db
    
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      JWT_SECRET_KEY: 271==4&c&#2m8a)ok#6l1r5ig&@!senzb(r*tdydc%f5iu@e8g

    ports:
      - "8000:8000"

    command: bash -c "fastapi dev --host 0.0.0.0 --port 8000"

    volumes:
      - ./core:/usr/src/core